### PR TITLE
Added XVG / Verge

### PR DESCRIPTION
**Pull request by billerl**
Added XVG / Verge also increased the decimal places to 8 to show down to 1 satoshi.
Changed the gitignore with one generated by https://gitignore.io/api/androidstudio. Feel free to keep yours if you accept the pull request.
I changed the Readme.md to indicate that this version is not on Google Play or F Droid.
Thanks for a great widget. Feel free to reach out with criticism or any advice.

### CODE REVIEW

**Comment by billerl** [comment]
also changed build.gradel minSdkVersion:
from:
minSdkVersion 19
to:
minSdkVersion 23
to eliminate deprecation warning with... something ( I can't remember)

**Comment by hwki** [comment]
created verge branch to clean up pull request before merging to master

**Comment by hwki** [comment]
merged, thanks

**Comment by billerl** [comment]
Great thank you. My first successful pull request.

**Pull request merged**
