### PR TITLE
Improved layout and added badges

### PR DESCRIPTION
**Pull request by PanderMusubi**
Two F-Droid badges are awaiting https://gitlab.com/fdroid/rfp/issues/265 which will be fixed soon.

### CODE REVIEW

**Comment by hwki** [comment]
Great, thanks. Will merge once apps are available on F-Droid

**Comment by PanderMusubi** [comment]
@hwki Can you please help out with the following: https://gitlab.com/fdroid/fdroiddata/merge_requests/2442 ? Thanks

**Comment by hwki** [comment]
@PanderMusubi I have added the proper tags. If you could please update your PR on F-Droid to use the version scheme "Auto Update Mode:Version btc-%v" for the bitcoin widget, "Auto Update Mode:Version eth-%v" for the ethereum, and "Auto Update Mode:Version ltc-%v" for the Litecoin.

**Comment by PanderMusubi** [comment]
Thanks. Made a new MR at F-Droid. Awaiting results from that.

**Comment by PanderMusubi** [comment]
All badges are available on F-Droid, you can merge this PR. :-)

**Comment by hwki** [comment]
The apps still aren't on F-Droid, just the request on their repo has been merged. Waiting until they appear.

**Comment by PanderMusubi** [comment]
Not on the site, but they are installable via the F-Droid client.

PS Before I create an issue: Is it true that tapping the Bitcoin widget triggers a reload with animation, but the other two widgets, it doesn't trigger a reload?

**Comment by hwki** [comment]
All the widgets should reload on tap. However, sometime some exchanges
return so quickly that the animation doesn't have time to show. I can look
into it the next time I find time to work on them.

**Pull request merged**
